name: test
on: pull_request
jobs:
    test:
        runs-on: docker
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-go@v4
          with:
              go-version: '>=1.22.0'
        - run: go build -v
